-- Auto-trigger a Vercel rebuild whenever merch_storefront_products changes,
-- so the static product pages generated by scripts/build-products.js
-- stay in sync with Supabase without manual intervention.

CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

CREATE OR REPLACE FUNCTION public.notify_vercel_storefront_changed()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, net
AS $$
BEGIN
  PERFORM net.http_post(
    url := 'https://api.vercel.com/v1/integrations/deploy/prj_u4G6kyZeIQVxttwDsWrfS6NHJGeZ/7xi5mUYRlY',
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := jsonb_build_object(
      'source', 'supabase',
      'table',  TG_TABLE_NAME,
      'op',     TG_OP,
      'fired_at', now()
    )
  );
  RETURN NULL;
END;
$$;

ALTER FUNCTION public.notify_vercel_storefront_changed() OWNER TO postgres;

DROP TRIGGER IF EXISTS storefront_products_redeploy ON public.merch_storefront_products;
CREATE TRIGGER storefront_products_redeploy
AFTER INSERT OR UPDATE OR DELETE ON public.merch_storefront_products
FOR EACH STATEMENT
EXECUTE FUNCTION public.notify_vercel_storefront_changed();

COMMENT ON FUNCTION public.notify_vercel_storefront_changed() IS
  'Fires a POST to the Vercel deploy hook for the komui.ru project when the storefront product set changes. Wired by trigger storefront_products_redeploy on merch_storefront_products.';
